development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:dc90307336db137562b232ab8e5420ff@grouper.redistogo.com:11130/
  channel_prefix: star-support_production
